# Generated by Django 5.1 on 2024-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='check_discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='check_discard',
            field=models.BooleanField(default=False),
        ),
    ]
