# Generated by Django 5.1 on 2024-10-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_paper_search_google'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper_search_google',
            old_name='list_dict_paper_info',
            new_name='list_dict_paper_info_from_google',
        ),
    ]
