# Generated by Django 5.1 on 2024-10-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_remove_paper_abstract_remove_paper_journal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper_Search_Google',
        ),
    ]
