# Generated by Django 5.1 on 2024-10-16 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_delete_paper_search_google'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Search_Google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
                ('list_dict_paper_info_from_google', models.JSONField(blank=True, null=True)),
                ('list_dup_remove_dict_pdf_info_from_journal', models.JSONField(blank=True, null=True)),
                ('list_related_paper_id', models.JSONField(blank=True, null=True)),
                ('date_searched', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
