# Generated by Django 5.1 on 2024-10-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_paper_search_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_search_google',
            name='user',
        ),
    ]
