# Generated by Django 5.1 on 2024-10-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_paper_search_google_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_search_google',
            name='list_dict_paper_info_from_google',
        ),
    ]
