# Generated by Django 5.1 on 2024-10-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_remove_paper_search_google_list_dict_paper_info_from_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google',
            name='list_dict_paper_searchengine_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
