# Generated by Django 5.1 on 2024-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_paper_search_google_list_dict_paper_searchengine_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google',
            name='list_dup_remove_dict_pdf_info_from_engine',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
