# Generated by Django 5.1 on 2024-10-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_paper_search_google_list_dup_remove_dict_pdf_info_from_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_study',
            name='paper_search_google_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.paper_search_google'),
        ),
        migrations.AddField(
            model_name='mysettings_study',
            name='paper_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.paper'),
        ),
    ]
