# Generated by Django 5.1 on 2024-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_mysettings_study_paper_search_google_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_study',
            name='list_history_search_google',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
