# Generated by Django 5.1 on 2024-10-21 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_alter_conference_user_alter_fda_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Search_Google_and_PubMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
                ('list_dict_paper_info_from_pubmed', models.JSONField(blank=True, null=True)),
                ('list_dict_paper_searchengine_info', models.JSONField(blank=True, null=True)),
                ('list_dup_remove_dict_pdf_info_from_engine', models.JSONField(blank=True, null=True)),
                ('list_dup_remove_dict_pdf_info_from_journal', models.JSONField(blank=True, null=True)),
                ('list_related_paper_id', models.JSONField(blank=True, null=True)),
                ('date_searched', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mysettings_study',
            name='paper_search_google_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.paper_search_google_and_pubmed'),
        ),
        migrations.DeleteModel(
            name='Paper_Search_Google',
        ),
    ]
