# Generated by Django 5.1 on 2024-10-21 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_paper_search_google_and_pubmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper_Search_Google_and_PubMed',
            new_name='Paper_Search_Google',
        ),
    ]
