# Generated by Django 5.1 on 2024-10-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_rename_paper_search_google_and_pubmed_paper_search_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_search_google',
            name='list_dict_paper_info_from_pubmed',
        ),
    ]
