# Generated by Django 5.1 on 2024-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_remove_paper_search_google_list_dict_paper_info_from_pubmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google',
            name='list_dict_paper_info_from_pubmed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
