# Generated by Django 5.1 on 2024-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0019_rename_paper_search_google_paper_search_google_and_pubmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_searchengine_info',
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_info_from_google',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
