# Generated by Django 5.1 on 2024-10-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0020_remove_paper_search_google_and_pubmed_list_dict_paper_searchengine_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='dict_pdf_info_from_journal',
            new_name='dict_paper_info',
        ),
        migrations.AddField(
            model_name='paper',
            name='pmcid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_paper_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
