# Generated by Django 5.1 on 2024-10-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0021_rename_dict_pdf_info_from_journal_paper_dict_paper_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='dict_paper_info',
            new_name='list_dict_paper_info',
        ),
    ]
