# Generated by Django 5.1 on 2024-10-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0022_rename_dict_paper_info_paper_list_dict_paper_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysettings_study',
            old_name='list_history_search_google',
            new_name='list_history_search_paper',
        ),
        migrations.RenameField(
            model_name='mysettings_study',
            old_name='paper_search_google_selected',
            new_name='paper_search_selected',
        ),
    ]
