# Generated by Django 5.1 on 2024-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0023_rename_list_history_search_google_mysettings_study_list_history_search_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
