# Generated by Django 5.1 on 2024-10-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0024_paper_search_google_and_pubmed_list_dict_paper_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='list_dict_paper_info',
            new_name='dict_paper_info',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='first_author',
            new_name='first_author_name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='first_author_organization',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
    ]
