# Generated by Django 5.1 on 2024-10-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0025_rename_list_dict_paper_info_paper_dict_paper_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='list_dict_paper_hierachy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='list_dict_reference_paper',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
