# Generated by Django 5.1 on 2024-10-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0027_alter_paper_doi_alter_paper_file_path_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='list_reference_paper_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
