# Generated by Django 5.1 on 2024-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0029_paper_list_report_dict_ref_paper_parsing_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='first_author_url',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
