# Generated by Django 5.1 on 2024-10-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0031_paper_list_author_paper_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='doi',
            new_name='doi_url',
        ),
    ]
