# Generated by Django 5.1 on 2024-10-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0032_rename_doi_paper_doi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
