# Generated by Django 5.1 on 2024-11-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0033_paper_doi_alter_paper_doi_url_alter_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='list_dict_author_paper',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
