# Generated by Django 5.1 on 2024-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0034_paper_list_dict_author_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pmid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
