# Generated by Django 5.1 on 2024-11-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0035_paper_pmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
