# Generated by Django 5.1 on 2024-11-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0036_paper_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='date_published',
        ),
    ]
