# Generated by Django 5.1 on 2024-11-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0037_remove_paper_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='check_download_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
