# Generated by Django 5.1 on 2024-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0038_paper_check_download_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_study',
            name='list_bookmarked_paper_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='list_bookmarked_user_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
