# Generated by Django 5.1 on 2024-11-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0039_mysettings_study_list_bookmarked_paper_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_info_from_my_favorite',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_info_from_voronoi_db',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
