# Generated by Django 5.1 on 2024-11-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0040_paper_search_google_and_pubmed_list_dict_paper_info_from_my_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_study',
            name='active_tab_collected_paper',
            field=models.CharField(blank=True, default='Reference'),
        ),
        migrations.AddField(
            model_name='mysettings_study',
            name='active_tab_searched_paper',
            field=models.CharField(blank=True, default='Pubmed'),
        ),
        migrations.AddField(
            model_name='mysettings_study',
            name='list_selected_options_paper_search',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
