# Generated by Django 5.1 on 2024-11-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0041_mysettings_study_active_tab_collected_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysettings_study',
            name='list_selected_options_paper_search',
            field=models.JSONField(blank=True, default=['all']),
        ),
    ]
