# Generated by Django 5.1 on 2024-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0042_alter_mysettings_study_list_selected_options_paper_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='dict_paper_info_from_google',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='dict_paper_info_from_pubmed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysettings_study',
            name='list_selected_options_paper_search',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
