# Generated by Django 5.1 on 2024-11-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0043_paper_dict_paper_info_from_google_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper_search_google_and_pubmed',
            old_name='list_paper_id',
            new_name='list_paper_id_from_pubmed',
        ),
    ]
