# Generated by Django 5.1 on 2024-11-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0044_rename_list_paper_id_paper_search_google_and_pubmed_list_paper_id_from_pubmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_paper_id_from_google',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
