# Generated by Django 5.1 on 2024-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0045_paper_search_google_and_pubmed_list_paper_id_from_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_info',
        ),
        migrations.RemoveField(
            model_name='paper_search_google_and_pubmed',
            name='list_dup_remove_dict_pdf_info_from_engine',
        ),
        migrations.RemoveField(
            model_name='paper_search_google_and_pubmed',
            name='list_dup_remove_dict_pdf_info_from_journal',
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_dict_paper_info_from_etc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_paper_id_from_etc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_paper_id_from_my_favorite',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_paper_id_from_voronoi_db',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
