# Generated by Django 5.1 on 2024-11-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0046_remove_paper_search_google_and_pubmed_list_dict_paper_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_search_google_and_pubmed',
            name='list_related_paper_id',
        ),
    ]
