# Generated by Django 5.1 on 2024-11-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0047_remove_paper_search_google_and_pubmed_list_related_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal_info',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
