# Generated by Django 5.1 on 2024-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0048_paper_journal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='list_selected_options_paper_search',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
