# Generated by Django 5.1 on 2024-11-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0049_paper_search_google_and_pubmed_list_selected_options_paper_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper_search_google_and_pubmed',
            old_name='list_selected_options_paper_search',
            new_name='list_selected_search_options',
        ),
    ]
