# Generated by Django 5.1 on 2024-12-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0050_rename_list_selected_options_paper_search_paper_search_google_and_pubmed_list_selected_search_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='article_url',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_url',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
