# Generated by Django 5.1 on 2024-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0051_paper_article_url_paper_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
