# Generated by Django 5.1 on 2024-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0052_paper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_search_google_and_pubmed',
            name='keyword_ordered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
