# Generated by Django 5.1 on 2024-12-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0053_paper_search_google_and_pubmed_keyword_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
