# Generated by Django 5.1 on 2025-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0054_paper_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='list_dict_paper_image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
