# Generated by Django 5.1 on 2024-08-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySettings_HansEnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.actor')),
                ('selected_actor_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.actor_pic')),
            ],
        ),
    ]
