# Generated by Django 5.1 on 2024-08-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0002_mysettings_hansent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysettings_hansent',
            old_name='selected_actor_pic',
            new_name='actor_pic_selected',
        ),
        migrations.RenameField(
            model_name='mysettings_hansent',
            old_name='selected_actor',
            new_name='actor_selected',
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='menu_selected',
            field=models.CharField(blank=True, choices=[('01', 'ACTOR'), ('02', 'PICTURE'), ('03', 'VIDEO')], default='01'),
        ),
    ]
