# Generated by Django 5.1 on 2024-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0004_mysettings_hansent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_discard',
            field=models.BooleanField(default=False),
        ),
    ]
