# Generated by Django 5.1 on 2024-08-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0006_mysettings_hansent_check_field_ascending_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_field_ascending_picture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_field_ascending_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='count_page_number_actor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='count_page_number_picture',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='count_page_number_video',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='list_searched_actor_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='list_searched_picture_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='list_searched_video_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_field_picture',
            field=models.CharField(blank=True, default='id', max_length=50),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_field_video',
            field=models.CharField(blank=True, default='id', max_length=50),
        ),
    ]
