# Generated by Django 5.1 on 2024-08-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0007_mysettings_hansent_check_field_ascending_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='actor_pic',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
