# Generated by Django 5.1 on 2024-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0008_actor_image_cover_actor_pic_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_pic',
            name='hashcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
