# Generated by Django 5.1 on 2024-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0009_actor_pic_hashcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='hashcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
