# Generated by Django 5.1 on 2024-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0011_picture_album_video_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_album',
            name='check_discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video_album',
            name='check_discard',
            field=models.BooleanField(default=False),
        ),
    ]
