# Generated by Django 5.1 on 2024-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0012_picture_album_check_discard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='list_dict_info_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
