# Generated by Django 5.1 on 2024-08-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0014_actor_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
