# Generated by Django 5.1 on 2024-08-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0015_actor_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='list_dict_profile_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='hashcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='list_dict_picture_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='hashcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='list_dict_video_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
