# Generated by Django 5.1 on 2024-08-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0016_actor_list_dict_profile_album_picture_album_hashcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysettings_hansent',
            name='actor_pic_selected',
        ),
        migrations.DeleteModel(
            name='Actor_Pic',
        ),
    ]
