# Generated by Django 5.1 on 2024-08-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0017_remove_mysettings_hansent_actor_pic_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='picture_album_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.picture_album'),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='video_album_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.video_album'),
        ),
    ]
