# Generated by Django 5.1 on 2024-08-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0018_mysettings_hansent_picture_album_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_album',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='date_released',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='studio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='date_released',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='video_album',
            name='studio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
