# Generated by Django 5.1 on 2024-08-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0019_picture_album_code_picture_album_date_released_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='list_actor_picture_id',
        ),
    ]
