# Generated by Django 5.1 on 2024-08-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0020_remove_actor_list_actor_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_album',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video_album',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
