# Generated by Django 5.1 on 2024-08-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0021_alter_picture_album_date_released_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image_cover',
        ),
    ]
