# Generated by Django 5.1 on 2024-08-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0022_remove_actor_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_field_ascending_music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='count_page_number_music',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='list_searched_music_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_field_music',
            field=models.CharField(blank=True, default='id', max_length=50),
        ),
        migrations.CreateModel(
            name='Music_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('hashcode', models.CharField(blank=True, max_length=250, null=True)),
                ('list_dict_music_album', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('studio', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.FloatField(default=0)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('check_discard', models.BooleanField(default=False)),
                ('main_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.actor')),
            ],
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='music_album_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.music_album'),
        ),
    ]
