# Generated by Django 5.1 on 2024-08-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0023_mysettings_hansent_check_field_ascending_music_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysettings_hansent',
            old_name='list_searched_music_id',
            new_name='list_searched_music_album_id',
        ),
        migrations.RenameField(
            model_name='mysettings_hansent',
            old_name='list_searched_picture_id',
            new_name='list_searched_picture_album_id',
        ),
        migrations.RenameField(
            model_name='mysettings_hansent',
            old_name='list_searched_video_id',
            new_name='list_searched_video_album_id',
        ),
    ]
