# Generated by Django 5.1 on 2024-08-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0024_rename_list_searched_music_id_mysettings_hansent_list_searched_music_album_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_album',
            name='list_dict_picture_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music_album',
            name='list_dict_video_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='list_dict_picture_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysettings_hansent',
            name='menu_selected',
            field=models.CharField(blank=True, choices=[('01', 'ACTOR'), ('02', 'PICTURE'), ('03', 'VIDEO'), ('04', 'MUSIC')], default='01'),
        ),
    ]
