# Generated by Django 5.1 on 2024-08-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0026_mysettings_hansent_list_dict_history_actor_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysettings_hansent',
            name='list_dict_history_actor_select',
        ),
    ]
