# Generated by Django 5.1 on 2024-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0027_remove_mysettings_hansent_list_dict_history_actor_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_album',
            name='list_dict_info_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='list_dict_info_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='list_dict_info_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
