# Generated by Django 5.1 on 2024-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0028_music_album_list_dict_info_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_album',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video_album',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
