# Generated by Django 5.1 on 2024-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0029_music_album_rating_picture_album_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_album',
            name='list_dict_related_actor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music_album',
            name='list_dict_related_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='list_dict_related_actor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='list_dict_related_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='list_dict_related_actor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='list_dict_related_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
