# Generated by Django 5.1 on 2024-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0030_music_album_list_dict_related_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_audio_is_playing_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_background_play_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_favorite_play_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_loop_play_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_music_player_expand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_repeat_play_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_shuffle_play_activated',
            field=models.BooleanField(default=False),
        ),
    ]
