# Generated by Django 5.1 on 2024-09-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0032_rename_evaluation_actor_score_actor_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_album',
            name='list_dict_video_album',
        ),
    ]
