# Generated by Django 5.1 on 2024-09-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0033_remove_music_album_list_dict_video_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('hashcode', models.CharField(blank=True, max_length=250, null=True)),
                ('list_dict_manga_album', models.JSONField(blank=True, null=True)),
                ('list_dict_info_url', models.JSONField(blank=True, null=True)),
                ('list_dict_related_album', models.JSONField(blank=True, null=True)),
                ('list_dict_related_actor', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('studio', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.FloatField(default=0)),
                ('rating', models.IntegerField(default=1)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('check_discard', models.BooleanField(default=False)),
                ('main_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.actor')),
            ],
        ),
    ]
