# Generated by Django 5.1 on 2024-09-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0034_manga_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_field_ascending_manga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='count_page_number_manga',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='list_searched_manga_album_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='manga_album_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hans_ent.manga_album'),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_field_manga',
            field=models.CharField(blank=True, default='id', max_length=50),
        ),
    ]
