# Generated by Django 5.1 on 2024-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0035_mysettings_hansent_check_field_ascending_manga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='list_dict_volume_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysettings_hansent',
            name='menu_selected',
            field=models.CharField(blank=True, choices=[('01', 'ACTOR'), ('02', 'PICTURE'), ('03', 'MANGA'), ('04', 'VIDEO'), ('05', 'MUSIC')], default='01'),
        ),
    ]
