# Generated by Django 5.1 on 2024-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0036_manga_album_list_dict_volume_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga_album',
            name='code',
        ),
        migrations.AddField(
            model_name='manga_album',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
