# Generated by Django 5.1 on 2024-09-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0037_remove_manga_album_code_manga_album_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga_album',
            old_name='list_dict_volume_info',
            new_name='list_dict_volume_manga',
        ),
    ]
