# Generated by Django 5.1 on 2024-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0038_rename_list_dict_volume_info_manga_album_list_dict_volume_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings_HansEnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_dict_nationality', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='category',
            field=models.CharField(blank=True, choices=[('01', 'ACTOR'), ('02', 'MODEL'), ('03', 'SINGER'), ('04', 'ENTERTAINER'), ('05', 'ADULT'), ('06', 'DIRECTOR'), ('07', 'WRITER'), ('08', 'LECTURER'), ('09', 'ETC')], default='01', max_length=50),
        ),
    ]
