# Generated by Django 5.1 on 2024-09-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0039_systemsettings_hansent_actor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga_album',
            old_name='volume',
            new_name='last_volume',
        ),
    ]
