# Generated by Django 5.1 on 2024-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0040_rename_volume_manga_album_last_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_album',
            name='category',
            field=models.CharField(blank=True, choices=[('01', 'ENTERTAINMENT'), ('02', 'STUDY'), ('03', 'MOVIE'), ('04', 'DRAMA'), ('04', 'MUSIC'), ('05', 'DOCUMENTARY'), ('06', 'ADULT'), ('07', 'VR'), ('08', 'ETC')], default='01', max_length=50),
        ),
    ]
