# Generated by Django 5.1 on 2024-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0041_video_album_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_album',
            name='check_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
