# Generated by Django 5.1 on 2024-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0043_systemsettings_hansent_list_dict_manga_id_parsing_wfwf'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='check_discard',
            field=models.BooleanField(default=False),
        ),
    ]
