# Generated by Django 5.1 on 2024-09-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0044_systemsettings_hansent_check_discard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings_hansent',
            old_name='list_dict_manga_id_parsing_wfwf',
            new_name='list_dict_manga_info_for_parsing',
        ),
    ]
