# Generated by Django 5.1 on 2024-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0045_rename_list_dict_manga_id_parsing_wfwf_systemsettings_hansent_list_dict_manga_info_for_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='parsing_base_url_manga',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
