# Generated by Django 5.1 on 2024-09-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0046_systemsettings_hansent_parsing_base_url_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='parsing_cover_img_url_manga',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
