# Generated by Django 5.1 on 2024-10-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0047_systemsettings_hansent_parsing_cover_img_url_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='list_dict_report_error_manga',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
