# Generated by Django 5.1 on 2024-10-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0048_systemsettings_hansent_list_dict_report_error_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_category_actor',
            field=models.CharField(blank=True, default=('00', 'ALL'), max_length=50),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_category_manga',
            field=models.CharField(blank=True, default=('00', 'ALL'), max_length=50),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_category_music',
            field=models.CharField(blank=True, default=('00', 'ALL'), max_length=50),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_category_picture',
            field=models.CharField(blank=True, default=('00', 'ALL'), max_length=50),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='selected_category_video',
            field=models.CharField(blank=True, default=('00', 'ALL'), max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', 'ENTERTAINER'), ('02', 'SINGER'), ('04', 'ACTOR'), ('05', 'ACTOR_ADULT'), ('06', 'AMATUER'), ('07', 'AMATUER_ADULT'), ('08', 'MODEL'), ('09', 'MODEL_ADULT'), ('10', 'SNS'), ('11', 'BJ'), ('12', 'PRIVITE'), ('13', 'AI'), ('15', 'DIRECTOR'), ('16', 'WRITER'), ('17', 'LECTURER'), ('19', 'ETC')], default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='video_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', 'ENTERTAINMENT'), ('02', 'STUDY'), ('03', 'MOVIE'), ('04', 'DRAMA'), ('04', 'MUSIC'), ('05', 'DOCUMENTARY'), ('06', 'ADULT'), ('07', 'VR'), ('08', 'ETC')], default='00', max_length=50),
        ),
    ]
