# Generated by Django 5.1 on 2024-10-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0049_mysettings_hansent_selected_category_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', '4KUP'), ('02', 'ENT'), ('03', 'AMA'), ('04', 'ETC')], default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='music_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', 'KPOP'), ('02', 'POP'), ('03', 'CLASSIC'), ('04', 'JAZZ'), ('05', 'ETC')], default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', '일상사진'), ('02', '일반화보'), ('03', '성인화보'), ('04', '일반기타'), ('05', '성인기타')], default='00', max_length=50),
        ),
    ]
