# Generated by Django 5.1 on 2024-10-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0051_alter_mysettings_hansent_selected_category_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', 'ENTERTAINER'), ('02', 'SINGER'), ('04', 'ACTOR'), ('05', 'ACTOR_ADULT'), ('06', 'AMATUER'), ('07', 'AMATUER_ADULT'), ('08', 'MODEL'), ('09', 'MODEL_ADULT'), ('10', 'SNS'), ('11', 'BJ'), ('12', 'PRIVITE'), ('13', 'AI'), ('15', 'DIRECTOR'), ('16', 'WRITER'), ('17', 'LECTURER'), ('19', 'ETC')], default='00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manga_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', '4KUP'), ('02', 'ENT'), ('03', 'AMA'), ('04', 'ETC')], default='00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='music_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', 'KPOP'), ('02', 'POP'), ('03', 'CLASSIC'), ('04', 'JAZZ'), ('05', 'ETC')], default='00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='picture_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', '일상사진'), ('02', '일반화보'), ('03', '성인화보'), ('04', '일반기타'), ('05', '성인기타')], default='00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', 'ENTERTAINMENT'), ('02', 'STUDY'), ('03', 'MOVIE'), ('04', 'DRAMA'), ('04', 'MUSIC'), ('05', 'DOCUMENTARY'), ('06', 'ADULT'), ('07', 'VR'), ('08', 'ETC')], default='00', max_length=50, null=True),
        ),
    ]
