# Generated by Django 5.1 on 2024-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0052_alter_actor_category_alter_manga_album_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='dict_manga_album_cover',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga_album',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', '국내성인'), ('02', '국내일반'), ('03', '해외성인'), ('04', '해외일반'), ('05', 'ETC')], default='00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mysettings_hansent',
            name='selected_category_manga',
            field=models.CharField(blank=True, choices=[('00', 'ALL'), ('01', '국내성인'), ('02', '국내일반'), ('03', '해외성인'), ('04', '해외일반'), ('05', 'ETC')], default='00', max_length=50),
        ),
    ]
