# Generated by Django 5.1 on 2024-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0053_manga_album_dict_manga_album_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='dict_actor_album_cover',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music_album',
            name='dict_music_album_cover',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='dict_picture_album_cover',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='dict_video_album_cover',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
