# Generated by Django 5.1 on 2024-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0054_actor_dict_actor_album_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='parsing_movie_page_completed',
            field=models.IntegerField(default=1),
        ),
    ]
