# Generated by Django 5.1 on 2024-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0055_systemsettings_hansent_parsing_movie_page_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='list_dict_report_error_picture',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='parsing_picture_page_completed',
            field=models.IntegerField(default=1),
        ),
    ]
