# Generated by Django 5.1 on 2024-10-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0056_systemsettings_hansent_list_dict_report_error_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_album',
            name='list_dict_picture_url_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
