# Generated by Django 5.1 on 2024-10-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0057_picture_album_list_dict_picture_url_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture_album',
            old_name='list_dict_picture_url_album',
            new_name='list_picture_url_album',
        ),
    ]
