# Generated by Django 5.1 on 2024-10-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0058_rename_list_dict_picture_url_album_picture_album_list_picture_url_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_album',
            name='picture_download_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
