# Generated by Django 5.1 on 2024-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0060_picture_album_check_4k_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='check_new_volume',
            field=models.BooleanField(default=False),
        ),
    ]
