# Generated by Django 5.1 on 2024-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0061_manga_album_check_new_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='list_done_cover_resize_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
