# Generated by Django 5.1 on 2024-10-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0062_systemsettings_hansent_list_done_cover_resize_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='list_dict_score_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga_album',
            name='list_dict_score_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music_album',
            name='list_dict_score_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='list_dict_score_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='list_dict_score_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
