# Generated by Django 5.1 on 2024-10-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0063_actor_list_dict_score_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='list_dict_score_history',
            new_name='dict_score_history',
        ),
        migrations.RenameField(
            model_name='manga_album',
            old_name='list_dict_score_history',
            new_name='dict_score_history',
        ),
        migrations.RenameField(
            model_name='music_album',
            old_name='list_dict_score_history',
            new_name='dict_score_history',
        ),
        migrations.RenameField(
            model_name='picture_album',
            old_name='list_dict_score_history',
            new_name='dict_score_history',
        ),
        migrations.RenameField(
            model_name='video_album',
            old_name='list_dict_score_history',
            new_name='dict_score_history',
        ),
    ]
