# Generated by Django 5.1 on 2024-10-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0064_rename_list_dict_score_history_actor_dict_score_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga_album',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music_album',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture_album',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video_album',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
