# Generated by Django 5.1 on 2024-10-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0065_alter_actor_rating_alter_manga_album_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_album',
            name='list_galllery_url_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
