# Generated by Django 5.1 on 2024-10-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0066_picture_album_list_galllery_url_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture_album',
            old_name='list_galllery_url_album',
            new_name='list_dict_gallery_info',
        ),
    ]
