# Generated by Django 5.1 on 2024-10-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0067_rename_list_galllery_url_album_picture_album_list_dict_gallery_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture_album',
            old_name='list_dict_gallery_info',
            new_name='dict_gallery_info',
        ),
    ]
