# Generated by Django 5.1 on 2024-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0069_rename_parsing_picture_page_completed_systemsettings_hansent_parsing_picture_start_page_reverse_coun'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='music_album',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video_album',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
