# Generated by Django 5.1 on 2024-12-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0070_manga_album_date_created_music_album_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='parsing_picture_end_page_4khd',
            field=models.IntegerField(default=713),
        ),
    ]
