# Generated by Django 5.1 on 2025-04-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0072_systemsettings_hansent_list_picture_id_parsing_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='check_completed',
            field=models.BooleanField(default=False),
        ),
    ]
