# Generated by Django 5.1 on 2025-04-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0073_manga_album_check_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga_album',
            name='id_manga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
