# Generated by Django 5.1 on 2025-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0074_manga_album_id_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='list_manga_album_my_bookmark',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
