# Generated by Django 5.1 on 2025-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0075_mysettings_hansent_list_manga_album_my_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_switch_manga_complete_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysettings_hansent',
            name='check_switch_manga_new_volume_update_only',
            field=models.BooleanField(default=False),
        ),
    ]
