# Generated by Django 5.1 on 2025-04-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0076_mysettings_hansent_check_switch_manga_complete_hide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='dict_gallery_info_for_crawling_image_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
