# Generated by Django 5.1 on 2025-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0077_systemsettings_hansent_dict_gallery_info_for_crawling_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='list_dict_stoage_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
