# Generated by Django 5.1 on 2025-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0078_systemsettings_hansent_list_dict_stoage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='selected_vault',
            field=models.CharField(blank=True, default='vault1', max_length=50),
        ),
        migrations.AddField(
            model_name='manga_album',
            name='selected_vault',
            field=models.CharField(blank=True, default='vault1', max_length=50),
        ),
        migrations.AddField(
            model_name='music_album',
            name='selected_vault',
            field=models.CharField(blank=True, default='vault1', max_length=50),
        ),
        migrations.AddField(
            model_name='picture_album',
            name='selected_vault',
            field=models.CharField(blank=True, default='vault1', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='selected_vault',
            field=models.CharField(blank=True, default='vault1', max_length=50),
        ),
        migrations.AddField(
            model_name='video_album',
            name='selected_vault',
            field=models.CharField(blank=True, default='vault1', max_length=50),
        ),
    ]
