# Generated by Django 5.1 on 2025-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0079_actor_selected_vault_manga_album_selected_vault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings_hansent',
            name='selected_picture_album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
