# Generated by Django 5.1 on 2025-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hans_ent', '0080_systemsettings_hansent_selected_picture_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_album',
            name='check_4k_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
